- name: installing tomcat8.6
  hosts: webserver
  become: yes
  vars_files: 
    - vars/tomcat_ubuntu_vars.yaml
  tasks:
    - name: Install java8
      apt:
        name: "{{java_package}}"
        update_cache: yes
        state: present
      when: ansible_facts['distribution']=="Ubuntu"
    - name: create group tomcat
      group: 
        name: "{{username}}"
        state: present
      when: ansible_facts['distribution']=="Ubuntu"
    - name: create tomcat user
      user: 
        name: "{{username}}"
        group: "{{username}}"
        create_home: yes
        home: "{{tomcat_installation_path}}"
        shell: /bin/false
        state: present
      when: ansible_facts['distribution']=="Ubuntu"
    - name: unzip package
      package: 
        name: "{{unzip_package}}"
        state: present
      when: ansible_facts['distribution']=="Ubuntu"
    - name: download tomcat
      get_url:
        url: "{{tomcat_download_source}}"
        dest: "{{tomcat_download_location}}"
      when: ansible_facts['distribution']=="Ubuntu"
    - name: fetch the stats of the downloaded file
      stat:
        path: "{{tomcat_installation_path}}"
      register: tomcat_download_result  
    - name: extract tomcat
      unarchive:
        src: "{{tomcat_download_location}}"
        dest: "{{tomcat_installation_path}}"
      when: ansible_facts['distribution']=="Ubuntu" and not tomcat_download_result.stat.exists
      notify:
        - create symlink
        - give recursive ownership
        - give execute permissions
    - name: create service
      template:
        src: tomcat.service.j2
        dest: /etc/systemd/system/tomcat.service
      when: ansible_facts['distribution']=="Ubuntu"
      notify: daemon reload and start tomcat
  handlers:
    - name: daemon reload and start tomcat
      systemd:
        name: tomcat
        daemon_reload: yes
        state: started
    - name: create symlink
      file:
        src: /opt/tomcat/apache-tomcat-8.5.61
        dest: "{{tomcat_home}}"
        owner: "{{username}}"
        group: "{{username}}"
        state: link
      when: ansible_facts['distribution']=="Ubuntu"
    - name: give recursive ownership
      file:
        path: "{{tomcat_installation_path}}"
        recurse: yes
        owner: "{{username}}"
    - name: give execute permissions
      file:
        path: "{{item}}"
        mode: "+x"
      loop: "{{tomcat_executables}}"
        
