---
# handlers file for sample
- name: daemon reload and start tomcat
  systemd:
    name: tomcat
    daemon_reload: yes
    state: started
- name: create symlink
  file:
    src: /opt/tomcat/apache-tomcat-8.5.61
    dest: "{{tomcat_home}}"
    owner: "{{username}}"
    group: "{{username}}"
    state: link
  when: ansible_facts['distribution']=="Ubuntu"
- name: give recursive ownership
  file:
    path: "{{tomcat_installation_path}}"
    recurse: yes
    owner: "{{username}}"
- name: give execute permissions
  file:
    path: "{{item}}"
    mode: "+x"
  loop: "{{tomcat_executables}}"
    